name: Go

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build binaries
      run: |
        mkdir -p dist
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/maprun-league-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/maprun-league

    - name: Test
      run: go test -v ./...

    - name: Upload Release Assets
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: maprun-league-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/maprun-league-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/**/maprun-league-*
